### ISSUE TITLE
Feature request: configurable ramp up/ down rate in NZW31S device handler

### ISSUE THREAD

**Issue by dortort** [InovelliUSA/SmartThingsInovelli#1]
Could you please add a configuration option for ramp up/ down rate in NZW31S device handler?

Also, an added ability to send an event to "blink" (x times on, pause, off, pause, and return to previous state) would be useful.

**Comment by InovelliUSA** [comment]
Cleaning up Github. This feature was not in the firmware for our NZW31, but is in the firmware for our new generation device LZW31.
